
package Vista;

import Modelo.Habitacion;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JTabbedPane;

public class PanelHabitacion extends javax.swing.JPanel {

    private Habitacion objHabitacion;
    
    public PanelHabitacion(Habitacion habitacion) {
        objHabitacion=habitacion;             
        initComponents();
        initComponentsHabitacion();
        
    }
    
    private void initComponentsHabitacion() {
    
     TxtPrecioTemAlta.setText(objHabitacion.getPrecio_temAlta()+" COP");
     TxtPrecioTemBaja.setText(objHabitacion.getPrecio_temBaja()+" COP");
     try{
            byte[] btDataFile = new sun.misc.BASE64Decoder().decodeBuffer(objHabitacion.getImagen_habitacion());;
            BufferedImage image = ImageIO.read(new ByteArrayInputStream(btDataFile));
            //ImagenHotel.setText(objHotel.getIma);
            ImagenHabitacion.setIcon(new ImageIcon(image));
            ImagenHabitacion.setSize(new Dimension(360,120));
        }catch(Exception e){
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTempAlt = new javax.swing.JLabel();
        TxtPrecioTemAlta = new javax.swing.JTextField();
        LblTempBaj = new javax.swing.JLabel();
        TxtPrecioTemBaja = new javax.swing.JTextField();
        ImagenHabitacion = new javax.swing.JLabel();
        BtnReserva = new javax.swing.JButton();

        setEnabled(false);
        setMinimumSize(new java.awt.Dimension(421, 479));

        LblTempAlt.setText("Tarifa Temporada Alta: ");

        TxtPrecioTemAlta.setText("Chorrosientos");
        TxtPrecioTemAlta.setEnabled(false);
        TxtPrecioTemAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrecioTemAltaActionPerformed(evt);
            }
        });

        LblTempBaj.setText("Tarifa Temporada Baja: ");

        TxtPrecioTemBaja.setText("Sientos");
        TxtPrecioTemBaja.setEnabled(false);
        TxtPrecioTemBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrecioTemBajaActionPerformed(evt);
            }
        });

        ImagenHabitacion.setMaximumSize(new java.awt.Dimension(300, 300));
        ImagenHabitacion.setMinimumSize(new java.awt.Dimension(300, 300));

        BtnReserva.setText("Reserva");
        BtnReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagenHabitacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblTempAlt)
                            .addComponent(LblTempBaj)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtPrecioTemAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtPrecioTemBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(BtnReserva)))
                        .addGap(0, 162, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImagenHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTempAlt)
                    .addComponent(TxtPrecioTemAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTempBaj)
                    .addComponent(TxtPrecioTemBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnReserva)
                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxtPrecioTemAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrecioTemAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrecioTemAltaActionPerformed

    private void TxtPrecioTemBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrecioTemBajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrecioTemBajaActionPerformed

    private void BtnReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReservaActionPerformed
        Registro panelRegistro = new Registro(objHabitacion);
        panelRegistro.setVisible(true);
    }//GEN-LAST:event_BtnReservaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnReserva;
    private javax.swing.JLabel ImagenHabitacion;
    private javax.swing.JLabel LblTempAlt;
    private javax.swing.JLabel LblTempBaj;
    private javax.swing.JTextField TxtPrecioTemAlta;
    private javax.swing.JTextField TxtPrecioTemBaja;
    // End of variables declaration//GEN-END:variables

    
}
