package Vista;

import Data.HabitacionData;
import Modelo.Habitacion;
import Modelo.Hotel;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

public class PanelHotel extends javax.swing.JPanel {

    private Hotel objHotel;


    public PanelHotel(Hotel hotel) {
        objHotel = hotel;
        initComponents();
        initComponentsHotel();

    }

    private void initComponentsHotel() {
        this.setName(objHotel.getNom_hotel());             
        try {
            
            byte[] btDataFile = new sun.misc.BASE64Decoder().decodeBuffer(objHotel.getImagen());;
            BufferedImage image = ImageIO.read(new ByteArrayInputStream(btDataFile));
            ImagenHotel.setSize(new Dimension(178,460));
            ImagenHotel.setIcon(new ImageIcon(image));
            
            HabitacionData habitacionesData = new HabitacionData();
            List<Habitacion> listaHabitaciones = habitacionesData.getHabitacionByHotelId(objHotel);
            if (!listaHabitaciones.isEmpty()) {
                initComponents();
                for (Habitacion habitacion : listaHabitaciones) {
                    PanelHabitacion panel = new PanelHabitacion(habitacion);                    
                    jTabbedPane2.add(habitacion.getNom_habitacion(), panel);
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImagenHotel = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();

        setMaximumSize(new java.awt.Dimension(421, 479));
        setMinimumSize(new java.awt.Dimension(421, 479));
        setPreferredSize(new java.awt.Dimension(421, 479));

        ImagenHotel.setMaximumSize(new java.awt.Dimension(421, 479));
        ImagenHotel.setMinimumSize(new java.awt.Dimension(421, 479));
        ImagenHotel.setName(""); // NOI18N

        jTabbedPane2.setMinimumSize(new java.awt.Dimension(421, 479));
        jTabbedPane2.setPreferredSize(new java.awt.Dimension(421, 479));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImagenHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ImagenHotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenHotel;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
